version: "3.7"
services:
  ehrbase_webservice:
    container_name: ehrbase-webservice
    image: regndsndp.azurecr.io/nes/ehrbase:0.9.0-nds-patch-3
    ports:
      - "38084:8080"
    networks:
      - "ehrbase-net"
    volumes:
      - ./file_repo:/file_repo
    environment:
      DB_URL: "jdbc:postgresql://ehrbase-db:5432/ehrbase"
      DB_USER: ehrbase
      DB_PASS: ehrbase
      SYSTEM_NAME: TEST
      OUTH2_REAL_NAME: demo
      OUTH2_CLIENT_NAME: myclient
      OUTH2_SERVER_URL: "http://example.com"

networks:
  ehrbase-net:
    name: ehrbase-net

